env:
  browser: true
  node: true
  es6: true
  commonjs: true
extends: 'eslint:recommended'
parser: babel-eslint
plugins:
  - html
  - flowtype
rules:
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - warn
    - unix
  quotes:
    - off
  semi:
    - error
    - never
  comma-dangle:
    - off
  no-console:
    - off
  no-unused-vars:
    - warn
